HM_arena:
  graphs:
    - src_stem: spatial-interference-locs2D
      title: 'Robot Collision Density'
    - src_stem: spatial-dist2D-pos
      title: 'Robot Occupancy Density'

HM_swarm:
  graphs:
    - src_stem: block-acq-locs2D
      title: 'Block Acquisition Locations'
    - src_stem: block-acq-vector-locs2D
      title: 'Block Acquisition Vector Locations'
    - src_stem: block-acq-explore-locs2D
      title: 'Block Acquisition Exploration Locations'
