base_graphs: &base_graphs
  - LN_fsm_collision
  - LN_fsm_movement
  - LN_block_trans
  - LN_block_acq
  - LN_block_manip
  - LN_convergence
  - LN_perception
  - HM_arena
  - HM_swarm

st:
  xml:
    attr_change:
      - ['.//loop_functions', 'label', 'construction_loop_functions']
      - ['.//qt-opengl/user_functions', 'label', 'construction_qt_user_functions']
  controllers:
    - name: FCRW_BST
      xml:
        attr_change:
          - ['.//controllers', '__controller__', 'fcrw_bst_controller']

      graphs_inherit:
        - *base_graphs
