perf:
  # inverted: true
  inverted: False

  intra_interference_csv: 'spatial-interference-counts.csv'
  intra_interference_col: 'cum_avg_exp_interference'

  intra_perf_csv: 'block-manipulation.csv'
  intra_perf_col: 'cum_avg_free_pickup_events'

  raw_perf_title: 'Block Acquisition Rate (Cumulative)'
  raw_perf_ylabel: 'Events/Timestep'

  # intra_perf_csv: 'block-transportee.csv'
  # intra_perf_col: 'cum_avg_transport_time'

  # raw_perf_title: 'Block Transport Time (Cumulative)'
  # raw_perf_ylabel: 'Timesteps'

  intra_tv_environment_csv: 'tv-environment.csv'
  intra_tv_population_csv: 'tv-population.csv'

  flexibility:
    hz: # [10,000] second periods
      - 0.00002

    M_amp:
      - 0.1
      - 0.15
      - 0.20
      - 0.25
      - 0.30
      - 0.35
      - 0.40
      - 0.45

  robustness:
    gaussian_ticks_mean_range: [0.0, 0.0]
    gaussian_ticks_stddev_range: [0.0, 0.05]
    gaussian_ticks_src: stddev
    gaussian_labels_show: stddev

    sensors:
      light:
        model: gaussian
        mean_range: [0.0, 0.0]
        stddev_range: [0.0, 0.05]
      proximity:
        model: gaussian
        mean_range: [0.0, 0.0]
        stddev_range: [0.0, 0.05]
      ground:
        model: gaussian
        mean_range: [0.0, 0.0]
        stddev_range: [0.0, 0.05]
      steering:
        model: gaussian
        mean_range: [0.0, 0.0]
        stddev_range: [0.0, 0.05]
      position:
        model: gaussian
        mean_range: [0.0, 0.0]
        stddev_range: [0.0, 0.05]

    actuators:
      steering:
        model: gaussian
        # Factor of 1.0 = normal operation, so inject noise around that setpoint
        mean_range: [1.0, 1.0]
        stddev_range: [0.0, 0.05]
